spring:
  application:
    name: core
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
        descriptor:
          sql: trace

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${postgres.local.url}
    username: ${postgres.local.username}
    password: ${postgres.local.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
---
